<style>
<?php if($block->getLang()=="ar"){ ?>
    .wpwl-group {
        direction: ltr !important;
    }

    .wpwl-control-cardNumber {
        direction: ltr !important;
        text-align: right;
    }

    .wpwl-brand-card {
        left: 8px !important;
        right: unset  !important;
    }
<?php } ?>
.wpwl-brand-card {
    display: block;
    visibility: visible;
    position: absolute;
    right: -8px;
    top: 5px;
    width: 65px;
    z-index: 10;
    float: right;
}
.wpwl-label-brand{
    display: none !important;
}
.wpwl-control-brand{
    display: none !important;
}
.wpwl-brand-MASTER{

    top:0px;

}
<?php echo $block->getCss();?>
</style>
<script
	src="https://code.jquery.com/jquery-3.3.1.min.js"
	integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	crossorigin="anonymous"></script>
<script>
    jq331 = jQuery.noConflict( true );
    function displayName(element) {
        jq331('.wpwl-brand-card').each(function () {
            jq331(element).append(this);
        });
    }
	var wpwlOptions = {
        locale: "<?php echo $block->getLang();?>",
        paymentTarget: "_top",
        style: "<?php echo $block->getStyle();?>",
        onReady: function () {
            jq331('.wpwl-wrapper-cardNumber').each(function () {
                displayName(this);
            });
            jq331('[name="form_key"]').remove();

        },
        applePay : {
            merchantCapabilities:["supports3DS"],
            supportedNetworks: ["amex", "masterCard", "visa", "mada"]
        }
    }
</script>
<script src="<?php echo $block->getFormUrl(); ?>"></script>
<?php if($block->getPaymentBrand() === 'APPLEPAY') {?>
    <h1><?php echo __('Please note,ApplePay only works on IOS and Safari browsers') ?></h1>
    <p><?php echo __('To proceed with the payment, please click on the below button') ?></p>
<?php } ?>
<form action="<?php echo $block->getShopperUrl(); ?>" class="paymentWidgets" data-brands="<?php echo $block->getPaymentBrand(); ?>"></form>
