<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 *
 * @package     Hyperpay
 * @copyright   Copyright (c) 2014 HYPERPAY
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * 
 */
?>
<?php
	$langs = Mage::helper('hyperpay')->getLocaleIsoCode(); 
	switch ($langs) {
		case 'de':
		case 'fr':
		case 'nl':
		case 'it':
		case 'ar':
		  $lang = $langs;
		  break;

		default:
		  $lang='en';
	}
?>
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>

<script>
    jq331 = jQuery.noConflict( true );
    var wpwlOptions = {
            locale: "<?php echo $lang;?>",
            paymentTarget: "_top",
            style: "<?php echo Mage::getSingleton('customer/session')->getStyle();?>",
            onReady: function(){
                    jq331('.wpwl-form-virtualAccount-STC_PAY .wpwl-wrapper-radio-qrcode').hide();
                    jq331('.wpwl-form-virtualAccount-STC_PAY .wpwl-wrapper-radio-mobile').hide();
                    jq331('.wpwl-form-virtualAccount-STC_PAY .wpwl-group-paymentMode').hide();
                    jq331('.wpwl-form-virtualAccount-STC_PAY .wpwl-group-mobilePhone').show();
                    jq331('.wpwl-form-virtualAccount-STC_PAY .wpwl-wrapper-radio-mobile .wpwl-control-radio-mobile').attr('checked',true);
                    jq331('.wpwl-form-virtualAccount-STC_PAY .wpwl-wrapper-radio-mobile .wpwl-control-radio-mobile').trigger('click');
        },
    

    };
    wpwlOptions.applePay = {
        merchantCapabilities:["supports3DS"],
        supportedNetworks: ["amex", "masterCard", "visa", "mada"]
    };
</script>
<script src="<?php echo Mage::getSingleton('customer/session')->getJsUrl();?>"></script>

<style>
    <?php if($lang=="ar"){ ?>
    .wpwl-wrapper-cardNumber,wpwl-group{
        direction: ltr !important;
    }
    <?php } ?>

    <?php echo Mage::getSingleton('customer/session')->getCss();?>
</style>
<form action="<?php echo Mage::getSingleton('customer/session')->getIframeFrontendResponse();?>" class="paymentWidgets" data-brands="<?php echo Mage::getSingleton('customer/session')->getIframeBrand();?>"></form>
